project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - Rmd/ca_factsheet_cyclist.qmd
    - Rmd/dft_pedestrian_factsheet.qmd
    - Rmd/ca_factsheet_pedestrian.qmd


website:
  title: "stats19_stats"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Rmd/dft_pedestrian_factsheet.qmd
        text: DfT Pedestrian factsheet
      - href: Rmd/ca_factsheet_pedestrian.qmd
        text: WECA Cyclist factsheet
      - href: Rmd/ca_factsheet_cyclist.qmd
        text: WECA Pedestrian factsheet
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



